---
kind: Template
apiVersion: v1
metadata:
  name: s2i-app-build
  annotations:
    openshift.io/display-name: S2I App Build Template
    description: S2I binary build config to create an image with your app baked in.
    iconClass: fa-cube
    tags: s2i
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "${NAME}"
      app: "${NAME}"
    name: "${NAME}"
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: "${NAME}"
      build: "${NAME}"
      name: "${NAME}-pipeline"
      type: pipeline
    name: "${NAME}-pipeline"
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: "${PIPELINE_CONTEXT_DIR}"
      git:
        ref: "${PIPELINE_SOURCE_REPOSITORY_REF}"
        uri: "${PIPELINE_SOURCE_REPOSITORY_URL}"
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: "${PIPELINE_FILENAME}"
      type: JenkinsPipeline
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: "${NAME}"
      build: "${NAME}"
      name: "${NAME}"
      type: image
    name: "${NAME}"
  spec:
    nodeSelector: 
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:latest"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: "${S2I_BASE_IMAGE}"
          namespace: openshift
      type: Source
  status:
    lastVersion: 1
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the resulting imagestream.
  required: true
  value: s2i-app
- name: PIPELINE_SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  description: The URL of the repository with your Jenkinsfile.
  required: true
- name: PIPELINE_SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default (master) branch.
  value: master
- name: PIPELINE_CONTEXT_DIR
  displayName: Git Context Directory for Jenkinsfile
  description: Set this to the directory where the Jenkinsfile is if not using the
    default root directory
- name: PIPELINE_FILENAME
  displayName: Name of Jenkinsfile
  description: Name of Jenkinsfile
  required: true
  value: Jenkinsfile
- name: S2I_BASE_IMAGE
  displayName: S2I Base Image for Application
  description: The base image for building the Application with S2I, including image
    tag
  required: true
  value: redhat-openjdk18-openshift:latest
