# Copyright 2018 Red Hat, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# I do not like that this thing exists. It;s need to test that the galaxy regex replace works, but it should go away soon for a better git repo structure.

- hosts: seed-hosts[0]
  vars:
    params_regexp_replace_pairs:
      - regexp: '^((?!.*DISPLAY_NAME))(.*NAMESPACE.*)=((?!.*{{ project_name_postfix }}))(.*)$'
        replace: '\2=\4{{ project_name_postfix }}'
      - regexp: '^(NAMESPACE_DISPLAY_NAME)=((?!.*\({{ project_name_postfix }}\)))(.*)$'
        replace: '\1=\3 ({{ project_name_postfix }})'
    galaxy_regexp_replace_pairs:
      - regexp: '(- src: )(https:\/\/github\.com\/rht-labs\/labs-ci-cd.*)((\n.*)+)(version: )(.*)'
        replace: '\1{{ scm_url }}\3\5{{ scm_ref }}'
  roles:
    - openshift-applier/roles/make-applier-projects-unique
    - openshift-applier/roles/openshift-applier
