---
- name: Create Projects and Policies
  hosts: bootstrap
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier

- name: Create CI/CD tools
  hosts: tools
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
      tags:
        - openshift-applier
    - name: set namespace
      set_fact:
        nexus_namespace: "{{ ci_cd_namespace }}"
        nexus_user: "admin"
        nexus_password: "admin123"
        nexus_api_base_path: /service/rest/v1
    - include_role:
        name: roles/infra-ansible/roles/config-nexus
      tags:
        - configure-nexus
