# This is the default playbook and will create a standard (relatively large) install.
---
- name: Create Projects and Policies
  hosts: bootstrap
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier

- name: Create CI/CD tools
  hosts: tools
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
      tags:
        - openshift-applier
