---
kind: Template
apiVersion: v1
metadata:
  name: jenkins-s2i
  annotations:
    openshift.io/display-name: Jenkins S2I
    description: Jenkins S2I build config to create a Jenkins image with your configuration
      baked in.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Keeps track of changes in the application image
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: jenkins-2-rhel7
    annotations:
      description: Tracks the Red Hat Jenkins base image, since openshift doesn't ship v3.7 tag in the default install. Importing the image to the labs-ci-cd namespsace, instead of openshift, allows normal users to run the playbook.
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.7
      importPolicy: {}
      name: v3.7
      referencePolicy:
        type: Source
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      build: "${NAME}"
      type: image
  spec:
    triggers:
    - type: GitHub
      github:
        secret: "${BUILD_SECRET}"
    - type: GitLab
      gitlab:
        secret: "${BUILD_SECRET}"
    - type: Generic
      generic:
        secret: "${BUILD_SECRET}"
        allowEnv: true
    - type: ConfigChange
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: "${SOURCE_REPOSITORY_CONTEXT_DIR}"
      sourceSecret:
        name: "${PIPELINE_SOURCE_SECRET}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: "${BUILDER_IMAGE_STREAM_TAG}"
          namespace: "${IMAGE_STREAM_NAMESPACE}"
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:latest"
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the resulting imagestream.
  required: true
  value: jenkins
- name: BUILD_SECRET
  displayName: Webhook Secret for builds
  description: A secret string used to configure the build webhooks.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
- name: PIPELINE_SOURCE_SECRET
  displayName: Secret for git repository
  description: The name of the OCP secret that has credentials for the pipeline git
    repository
  value: ''
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  description: The URL of the repository with your application source code.
  required: true
  value: https://github.com/rht-labs/openshift-jenkins-s2i-config.git
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default (master) branch.
- name: SOURCE_REPOSITORY_CONTEXT_DIR
  displayName: Git Reference
  description: The directory in the source repository where the SonarQube docker build is.
- name: BUILDER_IMAGE_STREAM_TAG
  displayName: Builder Image Stream Tag
  description: The Jenkins builder Image Stream Tag (e.g. jenkins:v3.7)
  required: true
  value: jenkins:v3.7
- name: IMAGE_STREAM_NAMESPACE
  displayName: Builder ImageSteam Tag
  description: The namespace where the Jenkins builder Image Stream lives
  required: true
  value: openshift
