---
kind: Template
apiVersion: v1
metadata:
  name: jenkins-pipeline-no-ocp-triggers
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "${NAME}"
      name: "${NAME}-pipeline"
      type: "pipeline"
    name: "${NAME}-pipeline"
  spec:
    runPolicy: "${RUN_POLICY}"
    source:
      contextDir: "${PIPELINE_CONTEXT_DIR}"
      git:
        ref: "${PIPELINE_SOURCE_REPOSITORY_REF}"
        uri: "${PIPELINE_SOURCE_REPOSITORY_URL}"
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: "${PIPELINE_FILENAME}"
      type: JenkinsPipeline
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the resulting imagestream.
  required: true
  value: s2i-app
- name: PIPELINE_SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  description: The URL of the repository with your Jenkinsfile.
  required: true
- name: PIPELINE_FILENAME
  displayName: Filename for the Jenkinsfle
  description: Filename for the Jenkinsfle
  required: true
  value: Jenkinsfile
- name: PIPELINE_SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default (master) branch.
  value: master
- name: PIPELINE_CONTEXT_DIR
  displayName: Git Context Directory for Jenkinsfile
  description: Set this to the directory where the Jenkinsfile is if not using the
    default root directory
- name: RUN_POLICY
  displayName: Run Policy
  description: Policy to control how the build runs
  value: Serial
  required: true